apiVersion: v1
kind: Service
metadata:
  name: bus-senegal-backend-svc
  labels:
    app: bus-senegal-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: bus-senegal-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP

