apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bus-senegal-frontend-ingress
  labels:
    app: bus-senegal-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: bus-senegal-frontend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bus-senegal-frontend-svc
            port:
              number: 3000

